name: Fantastic Maids
favicon: null
layout_spectrum: 0.8309992216527462
typography_spectrum: 0.8966115124057978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0428277812898159
  lightness: 0.22207858506590128
  saturation: 0.04956978443078697
  rhythmicContrast: 0.6377690718509257
purpose: []
